/**
 * apps/web/src/app/components/map/ChoroplethMap.tsx
 *
 * SYNAPSE — District choropleth map for Government Admin Dashboard
 * Uses Leaflet + GeoJSON (replaces Google Maps Datasets API + GADM polygon overlays)
 *
 * GeoJSON file: public/geojson/india_districts.geojson
 * Generated by: python scripts/load_gadm.py --country IN --level 3
 * Join key: feature.properties.GID_3 === district.admin_boundary_code
 */

"use client";

import { useEffect } from "react";
import { MapContainer, TileLayer, GeoJSON, useMap } from "react-leaflet";
import L from "leaflet";
import "leaflet/dist/leaflet.css";

export interface DistrictData {
  admin_boundary_code: string;  // e.g. "KA-DAKSHINA KANNADA"
  avg_urgency: number;          // 0–100
  total_needs: number;
  total_tasks: number;
  coverage_gap: boolean;        // avg_urgency ≥ 60 AND zero tasks in 14 days
}

interface ChoroplethMapProps {
  districtData: DistrictData[];
  geojson: GeoJSON.FeatureCollection;
  center?: [number, number];
  zoom?: number;
  onDistrictClick?: (district: DistrictData) => void;
}

// Build a lookup map for O(1) data access by boundary code
function buildLookup(data: DistrictData[]): Map<string, DistrictData> {
  return new Map(data.map((d) => [d.admin_boundary_code, d]));
}

// Choropleth fill colour based on avg_urgency
function choroplethColour(urgency: number, isCoverageGap: boolean): string {
  if (isCoverageGap) return "#7C3AED";  // purple — coverage gap (high need, no help)
  if (urgency >= 80) return "#EF4444";
  if (urgency >= 60) return "#F97316";
  if (urgency >= 40) return "#EAB308";
  if (urgency >= 20) return "#84CC16";
  return "#E5E7EB";                     // grey — no data
}

export default function ChoroplethMap({
  districtData,
  geojson,
  center = [20.5937, 78.9629],  // Centre of India
  zoom = 5,
  onDistrictClick,
}: ChoroplethMapProps) {
  const lookup = buildLookup(districtData);

  const styleFeature = (feature?: GeoJSON.Feature) => {
    const code = feature?.properties?.GID_3 ?? "";
    const data = lookup.get(code);
    const urgency = data?.avg_urgency ?? 0;
    const gap = data?.coverage_gap ?? false;

    return {
      fillColor: choroplethColour(urgency, gap),
      fillOpacity: 0.65,
      color: "#ffffff",
      weight: 0.8,
      opacity: 1,
    };
  };

  const onEachFeature = (feature: GeoJSON.Feature, layer: L.Layer) => {
    const code = feature?.properties?.GID_3 ?? "";
    const data = lookup.get(code);
    const districtName = feature?.properties?.NAME_3 ?? code;

    if (data) {
      (layer as L.Path).bindTooltip(
        `<div class="text-xs">
          <strong>${districtName}</strong><br/>
          Urgency: ${data.avg_urgency}/100<br/>
          Needs: ${data.total_needs} · Tasks: ${data.total_tasks}
          ${data.coverage_gap ? "<br/><span style='color:#7C3AED'>⚠ Coverage gap</span>" : ""}
        </div>`,
        { sticky: true }
      );

      (layer as L.Layer).on("click", () => {
        onDistrictClick?.(data);
      });
    }
  };

  return (
    <MapContainer
      center={center}
      zoom={zoom}
      style={{ height: "100%", width: "100%", borderRadius: "0.75rem" }}
    >
      <TileLayer
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        maxZoom={19}
        opacity={0.4}  // Dim base tiles — choropleth colours should dominate
      />

      {/* GeoJSON choropleth — replaces Google Maps Datasets API */}
      <GeoJSON
        key={JSON.stringify(districtData.map((d) => d.avg_urgency))}
        data={geojson}
        style={styleFeature}
        onEachFeature={onEachFeature}
      />
    </MapContainer>
  );
}
